feat: suggest similar function names on evaluation failure
When an unknown function is used, the CLI now shows up to 3 suggestions:

    Error: Unknown function: uper

    Did you mean?
      - upper (String: Convert to uppercase)
      - upper_first (String: Capitalize first letter)

Works in both normal mode and REPL mode.

Closes #33